#...............................................................................
#
#  This file is part of the Jancy toolkit.
#
#  Jancy is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/jancy/license.txt
#
#...............................................................................

dist:     trusty
sudo:     required
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - secure: Ifa4H3jsduRsiGSdQUYrH0G5dR4YJc40gusO7GkXpfX4TGNv0ANVI1sBwMhOgvgGTearCB5qWOk3R+JgvS3JRy7LFtLVjHemwOwpc4BE3/e71Xo9h38Ivbu8vUM+nnWzfweKYs2/JZbf0zGZIvd1MER0lxili1drbIzbnpMiu2nkjKLF+dQoUE311ZqKta4ixcvGwYGgi6fzGPY1S0VPRVt2YvFDPAZP55GHGYB7KCmr49ko/YB8vQQ+qGsi3BT4mIXzjVyTsx9cXHHrtCFffxbIQWmhiNQj6PAGAVWIkWfaQ1KIMYw+Ku7zOoMqC8ozDZX9OM8LIKFb0iOmFi4qdtUQcxWeGM+8ZgTWc66k+oyNliN8chGn5ondyT6UjVpUnFScIfax2y/4S2Ld6aD5b08ryDwlRiR9yVU5dKvPSvV55DgMEzoAdaC5qxO4a/RMAIxdxVUemrXM/Zg95KqlgtItl8GGuxyd4rzT+AWWAEUPY6qeDOgL74XPEBHi61r4XWwwTh45Opun6KAPZJr9Z5ZRyHTQ8Wko1JMLNN9iIvm3Yf+I5V6j/HqDPZVHXUZGbX9Wvy4GZNNr82HQmFK2Q5fmf6AI9SajzhuS+z8008oNEGtgI0wBxsH6RGVJm/Hu+++kDJvXLlkkxq190L4+6zGmTGsyP7CSxsrYXU72n3c=

    matrix:
        - LLVM_VERSION=3.4.2 TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
        - LLVM_VERSION=3.4.2 TARGET_CPU=x86 BUILD_CONFIGURATION=Release
        - LLVM_VERSION=3.4.2 TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
        - LLVM_VERSION=3.4.2 TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
        - LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
        - LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=x86 BUILD_CONFIGURATION=Release
        - LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
        - LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: LLVM_VERSION=3.4.2 TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: LLVM_VERSION=3.4.2 TARGET_CPU=x86 BUILD_CONFIGURATION=Release

        - os:  osx
          env: LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source ci/travis/set-env.sh
    - bash ci/travis/install-$TRAVIS_OS_NAME.sh
    - bash -e ci/travis/download-llvm.sh

    - git clone --depth 1 http://github.com/vovkos/axl
    - git clone --depth 1 http://github.com/vovkos/graco

script:
    - bash -e ci/travis/build.sh

notifications:
    webhooks:
        on_success: always
        on_failure: never
        on_error:   never
        on_cancel:  never

        urls:
            - http://jancy.org:5005/travis-ci

deploy:
    -   provider:      pages
        skip_cleanup:  true
        local_dir:     build/doc/html
        github_token:  $GITHUB_TOKEN

        on:
            branch:    master
            condition: $BUILD_DOC == ON

    -   provider:      script
        skip_cleanup:  true
        script:        bash $THIS_DIR/ci/travis/deploy-jancy-package.sh

        on:
            branch:    master
            condition: $DEPLOY_JANCY_PACKAGE == ON
